"""
Setup CLI for Superset Data Entry Plugin.
Run after pip install to generate init file and print config snippet.
"""
import argparse
import os

INIT_PLUGIN_CONTENT = '''"""
Generated by superset-data-entry-setup. Loads the Data Entry Plugin into Superset.
"""
import logging

logger = logging.getLogger(__name__)


def init_data_entry_plugin(app):
    """Register the Data Entry Plugin with Superset."""
    try:
        from superset_data_entry import register_plugin
        plugin_instance = register_plugin(app.appbuilder)
        logger.info("✅ Data Entry Plugin initialized successfully")
        return plugin_instance
    except ImportError as e:
        logger.warning("⚠️  Data Entry Plugin not installed: %s", e)
        return None
    except Exception as e:
        logger.error("❌ Plugin initialization failed: %s", e)
        return None
'''

CONFIG_SNIPPET = '''
# --- Superset Data Entry Plugin (add to superset_config.py) ---
def FLASK_APP_MUTATOR(app):
    try:
        import sys
        config_dir = os.path.dirname(os.path.abspath(__file__))
        if config_dir not in sys.path:
            sys.path.insert(0, config_dir)
        from superset_init_plugin import init_data_entry_plugin
        init_data_entry_plugin(app)
    except Exception as e:
        print("⚠️  Failed to load data entry plugin: %s" % e)
# --- End snippet ---
'''


def main():
    parser = argparse.ArgumentParser(
        description="Set up Superset Data Entry Plugin in your project. "
        "Creates superset_init_plugin.py and prints the config snippet for superset_config.py."
    )
    parser.add_argument(
        "--config-dir",
        "-C",
        default=".",
        help="Directory where superset_config.py lives (default: current directory). "
             "superset_init_plugin.py will be written here.",
    )
    parser.add_argument(
        "--force",
        "-f",
        action="store_true",
        help="Overwrite superset_init_plugin.py if it already exists.",
    )
    args = parser.parse_args()
    config_dir = os.path.abspath(args.config_dir)
    if not os.path.isdir(config_dir):
        print("Error: %s is not a directory." % config_dir)
        return 1
    init_path = os.path.join(config_dir, "superset_init_plugin.py")
    if os.path.exists(init_path) and not args.force:
        print("superset_init_plugin.py already exists at %s" % init_path)
        print("Use --force to overwrite. Printing config snippet only.\n")
    else:
        with open(init_path, "w", encoding="utf-8") as f:
            f.write(INIT_PLUGIN_CONTENT)
        print("Wrote %s\n" % init_path)
    print("Add the following to your superset_config.py (at the top, add: import os):")
    print(CONFIG_SNIPPET)
    print("Then restart Superset. Plugin tables will be created automatically on first load.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
